# Generated by Django 3.1 on 2021-04-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.AddField(
            model_name='order',
            name='pin_code',
            field=models.IntegerField(blank=True, default=1000),
            preserve_default=False,
        ),
    ]
